version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: corebank_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: corebankdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - corebank-net

  redis:
    image: redis:alpine
    container_name: corebank_redis
    ports:
      - "6379:6379"
    networks:
      - corebank-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: corebank_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - corebank-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: corebank_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - corebank-net


networks:
  corebank-net:

volumes:
  postgres_data:
