version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: corebank_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: corebankdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - corebank-net

  redis:
    image: redis:alpine
    container_name: corebank_redis
    ports:
      - "6379:6379"
    networks:
      - corebank-net

networks:
  corebank-net:

volumes:
  postgres_data:
